### ISSUE TITLE
Simulation error: "AccountNotFound"

### ISSUE THREAD

**Issue by fqinhong** [builderby/solana-swap-tutorial#2]
I ran the code and got the Simulation error: "AccountNotFound" error. How can I fix it?
![Snipaste_2024-08-21_14-43-51](https://github.com/user-attachments/assets/774a8238-1efd-4cbd-9f1d-29c10cb9af10)

**Comment by mflanagan1041** [comment]
I updated it to swap 0.01 SOL to USDC try again!

**Comment by mflanagan1041** [comment]
> I ran the code and got the Simulation error: "AccountNotFound" error. How can I fix it? ![Snipaste_2024-08-21_14-43-51](https://private-user-images.githubusercontent.com/7699533/359781470-774a8238-1efd-4cbd-9f1d-29c10cb9af10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTg2ODAsIm5iZiI6MTcyNDI1ODM4MCwicGF0aCI6Ii83Njk5NTMzLzM1OTc4MTQ3MC03NzRhODIzOC0xZWZkLTRjYmQtOWYxZC0yOWMxMGNiOWFmMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTYzOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUwZjhhMmU2MzQ1NTFhYTU1NTA3OGRjYjgwOWMzODFiNzcyMmFlY2E0Yjc4N2MyNjY5NmI3NTZjM2UzYzdmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.glk53FQlLxc0h44FaAfNXufoFMBW9qUXzf_rxdMgFCg)

I updated it to swap 0.01 SOL to USDC and fixed a VersionedTransaction issue.

**Comment by mflanagan1041** [comment]
I am closing this issue as it seems you closed it before. Just wanted to reply!
